site_name: Bosagora
nav:
  - Boascan Docs: index.md
  - Blocks::
      - Get latest blocks - GET /latest-blocks: getLatestBlocks.md
      - Get Block Height - GET /block_height: getBlockHeight.md
      - Get Block Height/:time- GET /block_height_at/:time: blockHeightat.md
      - Get Block Summary - GET /block-summary: blocksummary.md
      - Get Block Enrollments -  GET /block-enrollments: getBlockEnrollments.md
      - Get Block Transactions -  GET /block-transactions_by_Hash: getBlockTransactionsByHash.md
      - Get Block Transactions -  GET /block-transactions_by_Height: getBlockTransactionsByHeight.md
      
  - Validators::
      - Get Validators - GET /validators: getValidators.md 
      - Get Validators - GET /validators/:address: getValidatorAddress.md 
      - Get Validators - GET /validators/missed-blocks: getValidatorMissedBlocks.md 
      - Get Validators - GET /validators/block_validator: getBlockValidator.md 
      - Get Validators - GET /validators/validator_votes: getValidatorVotes.md 
      - Get Validators - GET /validators/validator_rewards: getValidatorRewards.md 

  - Wallet::
      - Get Wallet Transaction History - GET /wallet/transactions/history/:address: walletTransactionHistory.md 
      - Get Wallet Transaction Overview - GET /wallet/transaction/overview/:hash: walletTransactionOverview.md 
      - Get Wallet Block Header - GET /wallet/blocks/header: walletBlockHeader.md 
      - Get Wallet UTXO - GET /wallet/utxo/:address: walletUtxo.md 
      - Get Wallet Balance - GET /wallet/balance/:address: walletBalance.md 
      - Get Wallet Pending Transactions - GET wallet/transactions/pending/:address: walletPendingTransactions.md 
      - Get Wallet Transaction Details - GET wallet/transactions/details/: walletTransactionDetails.md 
      - Get Wallet Pending Transactions Overview - GET transactions/pending/overview: walletPendingTransactionsOverview.md 

  - Holders::
      - Get BOA Holders - GET /holders : getHolders.md 
      - Get BOA Holder - GET /holder/:address: getHolder.md 
      - Get HolderBalanceHistory - GET /holder_balance_history/:address: holderBalanceHistory.md
      
  - Fee::
      - Get average fee chart - GET /average_fee_chart : averageFeeChart.md 
      - Get transaction fee by size - GET /transaction_fee_by_size : transactionFeeBySize.md 

  - Search::
      - Get search  - GET /search/hash : search.md 

  - Coin Market::
      - Get Coin Market Chart  - GET /coinmarketchart : coinMarketChart.md 
      - Get Coin Market Cap for BOA. - GET /coinmarketcap : coinMarketCap.md  
      - Get Boa Stats. - GET /boa-stats: boa-stats.md 

  - Transactions::
      - Get Latest transactions - GET /latest-transactions : latestTransactions.md
      - Get transaction - GET /transaction/:hash : getTransaction.md
    #   - Get transaction fee -GET /transaction/fees/:tx_size: getTransactionFee.md
      - Get transaction status - GET /transaction/status/:hash: getTransactionStatus.md
      - Get pending transactions - GET /transaction/pending/:hash: getPendingTransaction.md

  - UTXO::
      - Get utxo  - GET /utxo/:address : getUTXO.md 
      - Get Wallet utxo  - GET /wallet/utxo/:address : getWalletUTXO.md 
      - Get txhash utxo  - GET /txhash/:utxo : getTxHashUTXO.md 
      
  - Proposals::
      - Get proposal list  - GET /proposals : getProposals.md 
      - Get proposal by proposal_id  - GET /proposals/proposal_id : getProposalsByID.md 
      - Get proposal voting Details - GET /voting_details/proposal_id: getVotingDetails.md 

theme:
  name: material
  custom_dir: docs/overrides/
  logo: img/logo.png

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
